spring:
  cloud:
    gateway:
      discovery: 
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        # 认证中心
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1  

security:
  encode:
    # 前端密码密钥，必须16位
    key: 'thanks,pig4cloud'

# 不校验验证码终端
ignore:
  clients:
    - test
