spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # JDBC连接Mysql6以上com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.233:3306/ordercenter?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: sql@kdn!123
    hikari:
      minimum-idle: 5 ## 最小空闲连接数量
      idle-timeout: 180000 ## 空闲连接存活最大时间，默认600000（10分钟
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
      auto-commit: true ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      maxLifetime: 600000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)


